version: "3"
services:
  main:
    container_name: main
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
      - docker.env
    # expose:
    #   - 5000
    # ports:
    #   - 5000:5000
    # command: npm run start:dev
    depends_on:
      - redis
      - postgres
      - mongo
    networks:
      - postgres
  redis:
    image: "redis:alpine"
    expose:
      - "6379"

  postgres:
    container_name: postgres
    image: postgres:latest
    volumes:
      - demo:/var/lib/postgresql/data
    env_file:
      - docker.env
      - ./.env
    networks:
      - postgres
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - ./data/mongo:/data/mongo
    ports:
      - 27017:27017
    networks:
      - postgres
    env_file:
      - docker.env
      - .env

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./conf.d/:/etc/nginx/conf.d
    depends_on:
      - main
      - redis
      - postgres
      - mongo
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
volumes:
  demo:
