name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  build:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: login docker
      uses: actions/checkout@v3
    - name: copy project
      uses: actions/checkout@v2
        
    - name: login docker
      run: |
       docker image build . --tag docker.pkg.github.com/dissmay/test-nginx-nestjs/test-nest
       docker push docker.pkg.github.com/dissmay/test-nginx-nestjs/test-nest:latest
