name: Docker Image CI
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: docker login1
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD |  docker login https://docker.pkg.github.com -u $DOCKER_USER --password-stdin
      - name: docker build node
        run: |
          docker image build . --tag docker.pkg.github.com/dissmay/test-nginx-nestjs/test-nest
      - name: docker push
        run: |
          docker push docker.pkg.github.com/dissmay/test-nginx-nestjs/test-nest:latest

  deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: 185.233.36.144
          username: root
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          script: |
            cd ./test-nginx-nestjs
            ls
  #   steps:
  #     - name: executing remote ssh commands using password
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: 185.233.36.144
  #         username: root
  #         password: tqazwr2123
  #         port: 22
  #         script: |
  #           cd ./test-nginx-nestjs
  #           docker-compose down
