name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: copy project
      uses: actions/checkout@v2
        
    - name: login docker
      run: |
       docker image build . --tag docker.pkg.github.com/dissmay/test-nginx-nestjs/test-nest
       echo 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 | docker login https://docker.pkg.github.com -u dissmay --password-stdin
       docker push docker.pkg.github.com/dissmay/test-nginx-nestjs/test-nest:latest
