name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: login docker
      uses: actions/checkout@v3
    - name: copy project
      uses: actions/checkout@v2
        
    - name: login docker
      run: |
       echo ${{ secrets.test-cicd }} | docker login https://docker.pkg.github.com -u dissmay --password-stdin
       docker image build . --tag docker.pkg.github.com/dissmay/test-nginx-nestjs/test-nest
       docker push docker.pkg.github.com/dissmay/test-nginx-nestjs/test-nest:latest
