name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: docker build python
      run: |
       docker image build . --tag docker.pkg.github.com/dissmay/test-nginx-nestjs/test-nest
    - name:  docker push
      run: |
       docker push docker.pkg.github.com/dissmay/test-nginx-nestjs/test-nest:latest
