name: Docker Image CI
on:
  push:
    branches: [ master ]

jobs:
#   build:
#     runs-on: ubuntu-latest
    
#     steps:
#     - uses: actions/checkout@v2
#     - name: docker login
#       env:
#         DOCKER_USER: ${{ secrets.DOCKER_USER }}
#         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
#       run: |
#         echo $DOCKER_PASSWORD |  docker login https://docker.pkg.github.com -u $DOCKER_USER --password-stdin
#     - name: docker build node
#       run: |
#        docker image build . --tag docker.pkg.github.com/dissmay/test-nginx-nestjs/test-nest
#     - name:  docker push
#       run: |
#        docker push docker.pkg.github.com/dissmay/test-nginx-nestjs/test-nest:latest
       
 
  deploy:
     runs-on: ubuntu-latest

     steps:
       - name: checkout
         uses: actions/checkout@v1
         
         
       - name: copy file via ssh key
         uses: ./
         with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          source: "tests/a.txt,tests/b.txt"
          target: "test
