name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: copy project
      uses: actions/checkout@v2
      
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
        
    - name: login docker
      run: |
       docker image build . --tag docker.pkg.github.com/dissmay/test-nginx-nestjs/test-nest
       docker push docker.pkg.github.com/dissmay/test-nginx-nestjs/test-nest:latest
